### ISSUE TITLE
Could you please give details about the parameter for this plugin?

### ISSUE THREAD

**Issue by yongxincen** [stulzq/kong-plugin-rate-limiting-ex#2]
Could you please give details about the parameters for this plugin like https://docs.konghq.com/hub/kong-inc/rate-limiting/?

Or at least let us know if there is any change to parameters to the official rate-limiting plugin,  the new parameter you've added.

I'm trying something like
`curl -i -X POST http://127.0.0.1:8001/services/xxx-service/plugins/ -d "name=rate-limiting-ex" -d "config.minute=5" -d "ip_header=xxx-header"`
but seems it's not a correct one.

**Comment by stulzq** [comment]
Only one parameter configuration "ip_header" has been added, and its corresponding logic

**Comment by stulzq** [comment]
Get real ip from custom http header, when you use CDN

**Comment by yongxincen** [comment]
So is the curl command I used above correct? I got below error when running it.

`HTTP/1.1 400 Bad Request
Date: Wed, 17 Apr 2019 01:35:29 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.14.0
Content-Length: 46

{"ip_header":"ip_header is an unknown field"}
`

**Comment by stulzq** [comment]
I have read the exception information of the previous issue. This plugin is currently unable to support the kong 1.0 version. If you want to implement it yourself, please check the official plugin development document.

**Comment by yongxincen** [comment]
From my last comment you can see, I've downgraded to kong/0.14.0 and test. Is this plugin working with this version of kong? If no, could you please provide the latest support version? Thanks.

**Comment by stulzq** [comment]
I forgot. It seems to be supportive. Sorry, I can't give you more information. I've planned to include him in the new version, but I can't give you a definite time. If you can, I hope you can submit a pull request.
